/* ============================================================
   config.js — Configuración de afiliados, suplementos e ingredientes

   INSTRUCCIONES PARA MONETIZACIÓN:
   1. Sustituye los valores AFFILIATE_* con tus URLs reales de afiliado
      (Amazon Associates, MyProtein, HSN, etc.)
   2. Los suplementos e ingredientes se cargan desde este fichero
      cuando la API no está disponible (modo offline/standalone).
   3. Las donaciones se configuran con DONATION_URL y BUYMECOFFEE_URL.
   ============================================================ */

window.HS_CONFIG = (function () {
  'use strict';

  // ── URLs de afiliado ───────────────────────────────────────────────────────
  // Sustituye con tus URLs reales. Ejemplo Amazon Associates:
  // https://www.amazon.es/dp/B07XYZ?tag=TU_TAG-21
  const AFFILIATE_LINKS = {
    AFFILIATE_WHEY:       'https://www.amazon.es/s?k=proteina+whey&tag=healthstackpro-21',
    AFFILIATE_CREATINE:   'https://www.amazon.es/s?k=creatina+monohidrato&tag=healthstackpro-21',
    AFFILIATE_CAFFEINE:   'https://www.amazon.es/s?k=cafeina+200mg+capsulas&tag=healthstackpro-21',
    AFFILIATE_OMEGA3:     'https://www.amazon.es/s?k=omega+3+EPA+DHA&tag=healthstackpro-21',
    AFFILIATE_VITAMIND:   'https://www.amazon.es/s?k=vitamina+D3+K2&tag=healthstackpro-21',
    AFFILIATE_MAGNESIUM:  'https://www.amazon.es/s?k=magnesio+bisglicinato&tag=healthstackpro-21',
    AFFILIATE_BETAALANINE:'https://www.amazon.es/s?k=beta+alanina&tag=healthstackpro-21',
    AFFILIATE_ZINC:       'https://www.amazon.es/s?k=zinc+gluconato&tag=healthstackpro-21',
  };

  // ── Donaciones y apoyo ─────────────────────────────────────────────────────
  const DONATION_LINKS = {
    PAYPAL:       'https://www.paypal.me/healthstackpro',
    BUYMECOFFEE:  'https://www.buymeacoffee.com/healthstack',
  };

  // ── Patrocinador (banner no intrusivo en footer) ───────────────────────────
  const SPONSOR = {
    name:    'MyProtein',
    tagline: 'Nutrición deportiva de calidad',
    url:     'https://www.myprotein.es/?affil=healthstackpro',
    logo:    '💪',   // Sustituir por <img> si se dispone de logo
    active:  true,   // false = oculta el banner
  };

  // ── Datos de suplementos (fallback si la API no responde) ──────────────────
  const SUPPLEMENTS = [
    {
      id: 1, sort_order: 1,
      name: 'Proteína Whey',
      dose: '20-40 g',
      timing: 'Post-entreno',
      level: 'essential',
      icon_emoji: '🥛',
      evidence_level: 'high',
      affiliate_link_placeholder: 'AFFILIATE_WHEY',
      description: 'La proteína de suero tiene el perfil de aminoácidos más completo y la mayor concentración de leucina (activador principal del mTOR). Resultados: +25-35% de fuerza y mayor volumen posible. Tómala los días que entrenes. Versión vegana: mezcla arroz + guisante.',
    },
    {
      id: 2, sort_order: 2,
      name: 'Creatina Monohidrato',
      dose: '3-5 g',
      timing: 'Cualquier hora (diario)',
      level: 'essential',
      icon_emoji: '⚡',
      evidence_level: 'high',
      affiliate_link_placeholder: 'AFFILIATE_CREATINE',
      description: 'El suplemento más estudiado de la historia del deporte. Mejora la potencia, la resistencia y la recuperación muscular. Resultado: +8-15% de fuerza. Tómala todos los días. No necesitas fase de carga.',
    },
    {
      id: 3, sort_order: 3,
      name: 'Cafeína',
      dose: '3-6 mg/kg',
      timing: '30-60 min antes del entreno',
      level: 'essential',
      icon_emoji: '☕',
      evidence_level: 'high',
      affiliate_link_placeholder: 'AFFILIATE_CAFFEINE',
      description: 'El estimulante más estudiado del mundo. Mejora la fuerza, la resistencia y reduce la percepción del esfuerzo. Para 70 kg: 200-400 mg. Evita tolerancia: úsala 3-4 días/semana.',
    },
    {
      id: 4, sort_order: 4,
      name: 'Omega-3 (EPA+DHA)',
      dose: '2-3 g EPA+DHA',
      timing: 'Con las comidas',
      level: 'optional',
      icon_emoji: '🐟',
      evidence_level: 'high',
      affiliate_link_placeholder: 'AFFILIATE_OMEGA3',
      description: 'Antiinflamatorio potente que mejora la recuperación muscular, la salud cardiovascular y la función cognitiva. Especialmente relevante si no consumes pescado azul 3+ veces por semana.',
    },
    {
      id: 5, sort_order: 5,
      name: 'Vitamina D3 + K2',
      dose: '2000-4000 UI D3',
      timing: 'Con la comida principal',
      level: 'optional',
      icon_emoji: '☀️',
      evidence_level: 'medium',
      affiliate_link_placeholder: 'AFFILIATE_VITAMIND',
      description: 'El 80% de la población tiene déficit en invierno. La D3 optimiza la testosterona, la función inmune y la densidad ósea. Tomar con K2 (100-200 mcg MK-7) para correcta distribución del calcio.',
    },
    {
      id: 6, sort_order: 6,
      name: 'Magnesio Bisglicinato',
      dose: '300-400 mg',
      timing: 'Antes de dormir',
      level: 'optional',
      icon_emoji: '🌙',
      evidence_level: 'medium',
      affiliate_link_placeholder: 'AFFILIATE_MAGNESIUM',
      description: 'Participa en más de 300 reacciones enzimáticas. Forma bisglicinato: mejor biodisponibilidad sin malestar digestivo. Mejora el sueño, reduce calambres musculares y optimiza la función nerviosa.',
    },
    {
      id: 7, sort_order: 7,
      name: 'Beta-Alanina',
      dose: '3.2-6.4 g',
      timing: 'Pre-entreno',
      level: 'optional',
      icon_emoji: '🔥',
      evidence_level: 'medium',
      affiliate_link_placeholder: 'AFFILIATE_BETAALANINE',
      description: 'Precursor de carnosina intramuscular, que actúa como tampón del ácido láctico en ejercicios de 1-4 minutos. Produce hormigueo (parestesia) inofensivo. Más efectiva en HIIT y circuitos.',
    },
    {
      id: 8, sort_order: 8,
      name: 'Zinc',
      dose: '15-30 mg',
      timing: 'Con la cena (lejos del calcio)',
      level: 'optional',
      icon_emoji: '💊',
      evidence_level: 'medium',
      affiliate_link_placeholder: 'AFFILIATE_ZINC',
      description: 'Interviene directamente en la síntesis de testosterona y GH. Los deportistas de fuerza tienen mayor riesgo de déficit. Tomar lejos de suplementos cálcicos. No superar 40 mg/día.',
    },
  ];

  // ── Datos de ingredientes (fallback si la API no responde) ─────────────────
  // Macros expresados por 100 g de producto
  const INGREDIENTS = [
    // Proteínas alta calidad
    { id:1,  name:'Pechuga de pollo',        category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:31.0, carbs:0.0,  fat:3.6,   calories:165, inflammation_base:'low' },
    { id:2,  name:'Pechuga de pavo',         category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:29.0, carbs:0.0,  fat:2.5,   calories:135, inflammation_base:'low' },
    { id:3,  name:'Salmón',                  category:'protein_high',   quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:25.0, carbs:0.0,  fat:13.0,  calories:208, inflammation_base:'low' },
    { id:4,  name:'Atún en agua',            category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:26.0, carbs:0.0,  fat:1.0,   calories:116, inflammation_base:'low' },
    { id:5,  name:'Clara de huevo',          category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:11.0, carbs:0.7,  fat:0.2,   calories:52,  inflammation_base:'low' },
    { id:6,  name:'Huevo entero',            category:'protein_high',   quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:13.0, carbs:1.1,  fat:11.0,  calories:155, inflammation_base:'low' },
    { id:7,  name:'Ternera magra',           category:'protein_high',   quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:26.0, carbs:0.0,  fat:9.0,   calories:189, inflammation_base:'medium' },
    { id:8,  name:'Merluza',                 category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:17.0, carbs:0.0,  fat:1.3,   calories:82,  inflammation_base:'low' },
    { id:9,  name:'Proteína Whey en polvo',  category:'protein_high',   quality:'high',   calorie_density:'medium', satiety_index:'medium', protein:75.0, carbs:8.0,  fat:4.0,   calories:370, inflammation_base:'low' },
    { id:10, name:'Requesón',                category:'protein_medium', quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:14.0, carbs:3.3,  fat:4.0,   calories:105, inflammation_base:'low' },
    { id:11, name:'Yogur griego 0%',         category:'protein_medium', quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:10.0, carbs:4.0,  fat:0.4,   calories:59,  inflammation_base:'low' },
    { id:12, name:'Tofu firme',              category:'protein_medium', quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:8.0,  carbs:1.9,  fat:4.8,   calories:76,  inflammation_base:'low' },
    { id:13, name:'Tempeh',                  category:'protein_medium', quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:19.0, carbs:9.0,  fat:11.0,  calories:193, inflammation_base:'low' },
    // Carbohidratos
    { id:14, name:'Avena',                   category:'carb_high',      quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:13.0, carbs:67.0, fat:7.0,   calories:379, inflammation_base:'low' },
    { id:15, name:'Arroz integral',          category:'carb_high',      quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:2.7,  carbs:23.0, fat:0.9,   calories:111, inflammation_base:'low' },
    { id:16, name:'Arroz blanco (cocido)',   category:'carb_high',      quality:'medium', calorie_density:'low',    satiety_index:'medium', protein:2.7,  carbs:28.0, fat:0.3,   calories:130, inflammation_base:'low' },
    { id:17, name:'Quinoa (cocida)',         category:'carb_high',      quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:4.4,  carbs:21.0, fat:1.9,   calories:120, inflammation_base:'low' },
    { id:18, name:'Patata (cocida)',         category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:2.0,  carbs:17.0, fat:0.1,   calories:77,  inflammation_base:'low' },
    { id:19, name:'Boniato',                 category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:1.6,  carbs:20.0, fat:0.1,   calories:86,  inflammation_base:'low' },
    { id:20, name:'Plátano',                 category:'carb_high',      quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.1,  carbs:23.0, fat:0.3,   calories:89,  inflammation_base:'low' },
    { id:21, name:'Pan integral',            category:'carb_medium',    quality:'medium', calorie_density:'medium', satiety_index:'medium', protein:9.0,  carbs:41.0, fat:3.0,   calories:247, inflammation_base:'low' },
    { id:22, name:'Pasta integral (cocida)', category:'carb_high',      quality:'medium', calorie_density:'low',    satiety_index:'medium', protein:5.3,  carbs:25.0, fat:0.9,   calories:124, inflammation_base:'low' },
    { id:23, name:'Garbanzos (cocidos)',     category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:8.9,  carbs:27.0, fat:2.6,   calories:164, inflammation_base:'low' },
    { id:24, name:'Lentejas (cocidas)',      category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:9.0,  carbs:20.0, fat:0.4,   calories:116, inflammation_base:'low' },
    // Grasas saludables
    { id:25, name:'Aguacate',               category:'fat_medium',     quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:2.0,  carbs:9.0,  fat:15.0,  calories:160, inflammation_base:'low' },
    { id:26, name:'Aceite de oliva AOVE',   category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'low',    protein:0.0,  carbs:0.0,  fat:100.0, calories:884, inflammation_base:'low' },
    { id:27, name:'Nueces',                 category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:15.0, carbs:14.0, fat:65.0,  calories:654, inflammation_base:'low' },
    { id:28, name:'Almendras',              category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:21.0, carbs:22.0, fat:50.0,  calories:579, inflammation_base:'low' },
    { id:29, name:'Mantequilla cacahuete',  category:'fat_high',       quality:'medium', calorie_density:'high',   satiety_index:'high',   protein:25.0, carbs:20.0, fat:50.0,  calories:598, inflammation_base:'low' },
    // Verduras y micronutrientes
    { id:30, name:'Espinacas',              category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:2.9,  carbs:3.6,  fat:0.4,   calories:23,  inflammation_base:'low' },
    { id:31, name:'Brócoli',                category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:2.8,  carbs:7.0,  fat:0.4,   calories:34,  inflammation_base:'low' },
    { id:32, name:'Zanahoria',              category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.9,  carbs:10.0, fat:0.2,   calories:41,  inflammation_base:'low' },
    { id:33, name:'Frutos rojos (mix)',     category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.7,  carbs:14.0, fat:0.3,   calories:57,  inflammation_base:'low' },
    { id:34, name:'Leche entera',           category:'mixed',          quality:'medium', calorie_density:'low',    satiety_index:'medium', protein:3.2,  carbs:4.8,  fat:3.5,   calories:61,  inflammation_base:'low' },
    { id:35, name:'Leche desnatada',        category:'protein_medium', quality:'medium', calorie_density:'low',    satiety_index:'medium', protein:3.5,  carbs:5.0,  fat:0.1,   calories:34,  inflammation_base:'low' },
    // Más proteínas de calidad
    { id:36, name:'Sardinas al natural',    category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:24.0, carbs:0.0,  fat:3.0,   calories:127, inflammation_base:'low' },
    { id:37, name:'Bacalao',                category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:20.0, carbs:0.0,  fat:0.7,   calories:82,  inflammation_base:'low' },
    { id:38, name:'Gambas / Langostinos',   category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:24.0, carbs:0.0,  fat:1.0,   calories:99,  inflammation_base:'low' },
    { id:39, name:'Pavo picado (magro)',    category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:22.0, carbs:0.0,  fat:8.0,   calories:163, inflammation_base:'low' },
    { id:40, name:'Edamame (cocido)',       category:'protein_medium', quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:11.0, carbs:8.5,  fat:5.2,   calories:122, inflammation_base:'low' },
    { id:41, name:'Queso cottage',         category:'protein_medium', quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:11.0, carbs:3.4,  fat:4.3,   calories:98,  inflammation_base:'low' },
    { id:42, name:'Lomo de cerdo magro',   category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:22.0, carbs:0.0,  fat:6.0,   calories:143, inflammation_base:'low' },
    { id:43, name:'Calamar / Pota',        category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:18.0, carbs:3.0,  fat:1.5,   calories:92,  inflammation_base:'low' },
    // Frutas
    { id:44, name:'Manzana',               category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.3,  carbs:14.0, fat:0.2,   calories:52,  inflammation_base:'low' },
    { id:45, name:'Naranja',               category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.9,  carbs:12.0, fat:0.1,   calories:47,  inflammation_base:'low' },
    { id:46, name:'Fresas',                category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.8,  carbs:7.7,  fat:0.3,   calories:32,  inflammation_base:'low' },
    { id:47, name:'Arándanos',             category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.7,  carbs:14.0, fat:0.3,   calories:57,  inflammation_base:'low' },
    { id:48, name:'Mango',                 category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.8,  carbs:15.0, fat:0.4,   calories:60,  inflammation_base:'low' },
    { id:49, name:'Kiwi',                  category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.1,  carbs:15.0, fat:0.5,   calories:61,  inflammation_base:'low' },
    { id:50, name:'Uvas',                  category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.7,  carbs:17.0, fat:0.2,   calories:67,  inflammation_base:'low' },
    { id:51, name:'Pera',                  category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.4,  carbs:15.0, fat:0.1,   calories:57,  inflammation_base:'low' },
    { id:52, name:'Sandía',                category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.6,  carbs:7.6,  fat:0.2,   calories:30,  inflammation_base:'low' },
    { id:53, name:'Cereza',                category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.0,  carbs:16.0, fat:0.3,   calories:63,  inflammation_base:'low' },
    { id:54, name:'Piña',                  category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.5,  carbs:13.0, fat:0.1,   calories:50,  inflammation_base:'low' },
    { id:55, name:'Melocotón',             category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.9,  carbs:10.0, fat:0.3,   calories:39,  inflammation_base:'low' },
    // Verduras
    { id:56, name:'Tomate',                category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.9,  carbs:3.9,  fat:0.2,   calories:18,  inflammation_base:'low' },
    { id:57, name:'Pimiento rojo',         category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.0,  carbs:6.0,  fat:0.3,   calories:31,  inflammation_base:'low' },
    { id:58, name:'Pimiento verde',        category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.9,  carbs:4.6,  fat:0.2,   calories:20,  inflammation_base:'low' },
    { id:59, name:'Pepino',                category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.7,  carbs:3.6,  fat:0.1,   calories:15,  inflammation_base:'low' },
    { id:60, name:'Lechuga romana',        category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.2,  carbs:3.3,  fat:0.3,   calories:17,  inflammation_base:'low' },
    { id:61, name:'Kale (col rizada)',     category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:4.3,  carbs:9.0,  fat:0.9,   calories:49,  inflammation_base:'low' },
    { id:62, name:'Champiñones',           category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:3.1,  carbs:3.3,  fat:0.3,   calories:22,  inflammation_base:'low' },
    { id:63, name:'Cebolla',               category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.1,  carbs:9.3,  fat:0.1,   calories:40,  inflammation_base:'low' },
    { id:64, name:'Calabacín',             category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.2,  carbs:3.1,  fat:0.3,   calories:17,  inflammation_base:'low' },
    { id:65, name:'Berenjena',             category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.0,  carbs:6.0,  fat:0.2,   calories:25,  inflammation_base:'low' },
    { id:66, name:'Coliflor',              category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.9,  carbs:5.0,  fat:0.3,   calories:25,  inflammation_base:'low' },
    { id:67, name:'Coles de Bruselas',     category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:3.4,  carbs:9.0,  fat:0.3,   calories:43,  inflammation_base:'low' },
    // Snacks saludables
    { id:68, name:'Chocolate negro 85%',   category:'mixed',          quality:'high',   calorie_density:'high',   satiety_index:'medium', protein:11.5, carbs:13.0, fat:43.0,  calories:501, inflammation_base:'low' },
    { id:69, name:'Hummus',                category:'mixed',          quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:8.0,  carbs:14.0, fat:9.0,   calories:166, inflammation_base:'low' },
    { id:70, name:'Galletas de avena',     category:'carb_medium',    quality:'high',   calorie_density:'medium', satiety_index:'medium', protein:6.0,  carbs:64.0, fat:10.0,  calories:370, inflammation_base:'low' },
    { id:71, name:'Barrita proteica',      category:'mixed',          quality:'medium', calorie_density:'medium', satiety_index:'medium', protein:20.0, carbs:30.0, fat:10.0,  calories:290, inflammation_base:'low' },
    { id:72, name:'Mix frutos secos',      category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:12.0, carbs:16.0, fat:52.0,  calories:571, inflammation_base:'low' },
    { id:73, name:'Tortas de arroz',       category:'carb_medium',    quality:'medium', calorie_density:'medium', satiety_index:'low',    protein:7.0,  carbs:80.0, fat:1.0,   calories:381, inflammation_base:'low' },
    { id:74, name:'Palomitas (sin grasa)', category:'carb_medium',    quality:'medium', calorie_density:'low',    satiety_index:'medium', protein:3.5,  carbs:74.0, fat:4.0,   calories:375, inflammation_base:'low' },
    // Grasas de calidad
    { id:75, name:'Semillas de chía',      category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:16.5, carbs:42.1, fat:30.7,  calories:486, inflammation_base:'low' },
    { id:76, name:'Semillas de lino',      category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:18.3, carbs:28.9, fat:42.2,  calories:534, inflammation_base:'low' },
    { id:77, name:'Tahini (pasta sésamo)', category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'medium', protein:17.0, carbs:21.0, fat:54.0,  calories:595, inflammation_base:'low' },
    { id:78, name:'Mantequilla almendra',  category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:21.0, carbs:20.0, fat:56.0,  calories:634, inflammation_base:'low' },
    { id:79, name:'Semillas de girasol',   category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:20.8, carbs:20.0, fat:51.0,  calories:584, inflammation_base:'low' },
    { id:80, name:'Pistachos',             category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:20.2, carbs:27.5, fat:45.4,  calories:562, inflammation_base:'low' },
    { id:81, name:'Semillas de calabaza',  category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:30.2, carbs:10.7, fat:49.1,  calories:559, inflammation_base:'low' },
    { id:82, name:'Aceite de coco virgen', category:'fat_high',       quality:'medium', calorie_density:'high',   satiety_index:'low',    protein:0.0,  carbs:0.0,  fat:100.0, calories:862, inflammation_base:'low' },
    // Proteínas fitness adicionales
    { id:83,  name:'Caseína en polvo',          category:'protein_high',   quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:82.0, carbs:4.0,  fat:1.0,   calories:355, inflammation_base:'low' },
    { id:84,  name:'Proteína vegana (guisante)', category:'protein_high',  quality:'high',   calorie_density:'medium', satiety_index:'medium', protein:77.0, carbs:6.0,  fat:3.0,   calories:363, inflammation_base:'low' },
    { id:85,  name:'Seitán',                    category:'protein_high',   quality:'medium', calorie_density:'medium', satiety_index:'high',   protein:25.0, carbs:14.0, fat:2.0,   calories:185, inflammation_base:'low' },
    { id:86,  name:'Soja texturizada (TVP)',    category:'protein_high',   quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:51.0, carbs:30.0, fat:3.4,   calories:334, inflammation_base:'low' },
    { id:87,  name:'Kéfir natural',             category:'protein_medium', quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:3.5,  carbs:4.5,  fat:3.5,   calories:63,  inflammation_base:'low' },
    { id:88,  name:'Trucha',                    category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:20.0, carbs:0.0,  fat:6.5,   calories:141, inflammation_base:'low' },
    { id:89,  name:'Lubina / Dorada',           category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:18.4, carbs:0.0,  fat:2.0,   calories:97,  inflammation_base:'low' },
    { id:90,  name:'Mejillones (cocidos)',       category:'protein_high',   quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:18.0, carbs:7.0,  fat:2.0,   calories:121, inflammation_base:'low' },
    { id:91,  name:'Queso parmesano',           category:'protein_high',   quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:38.0, carbs:0.0,  fat:26.0,  calories:392, inflammation_base:'low' },
    // Carbohidratos fitness adicionales
    { id:92,  name:'Pan de centeno integral',   category:'carb_medium',    quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:8.5,  carbs:48.0, fat:2.6,   calories:259, inflammation_base:'low' },
    { id:93,  name:'Pasta de legumbre',         category:'carb_high',      quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:22.0, carbs:58.0, fat:4.0,   calories:350, inflammation_base:'low' },
    { id:94,  name:'Cuscús (cocido)',           category:'carb_high',      quality:'medium', calorie_density:'low',    satiety_index:'medium', protein:3.8,  carbs:23.0, fat:0.2,   calories:112, inflammation_base:'low' },
    { id:95,  name:'Remolacha (cocida)',        category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.7,  carbs:10.0, fat:0.2,   calories:44,  inflammation_base:'low' },
    { id:96,  name:'Maíz dulce (cocido)',       category:'carb_medium',    quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:3.3,  carbs:19.0, fat:1.4,   calories:96,  inflammation_base:'low' },
    { id:97,  name:'Dátiles',                  category:'carb_high',      quality:'high',   calorie_density:'high',   satiety_index:'medium', protein:2.5,  carbs:75.0, fat:0.4,   calories:282, inflammation_base:'low' },
    // Especiales fitness
    { id:98,  name:'Aceite MCT',               category:'fat_high',       quality:'high',   calorie_density:'high',   satiety_index:'low',    protein:0.0,  carbs:0.0,  fat:100.0, calories:884, inflammation_base:'low' },
    { id:99,  name:'Cacao puro en polvo',      category:'mixed',          quality:'high',   calorie_density:'medium', satiety_index:'medium', protein:19.6, carbs:57.9, fat:13.7,  calories:228, inflammation_base:'low' },
    { id:100, name:'Rúcula',                   category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:2.6,  carbs:3.7,  fat:0.7,   calories:25,  inflammation_base:'low' },
    { id:101, name:'Miso (pasta fermentada)',  category:'mixed',          quality:'high',   calorie_density:'medium', satiety_index:'medium', protein:11.0, carbs:25.0, fat:3.0,   calories:182, inflammation_base:'low' },
    { id:102, name:'Miel pura',                category:'carb_high',      quality:'medium', calorie_density:'high',   satiety_index:'low',    protein:0.3,  carbs:82.0, fat:0.0,   calories:304, inflammation_base:'low' },
    // Legumbres adicionales
    { id:103, name:'Judías blancas (cocidas)', category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:9.0,  carbs:23.0, fat:0.5,   calories:139, inflammation_base:'low' },
    { id:104, name:'Judías negras (cocidas)',  category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:8.9,  carbs:23.7, fat:0.5,   calories:132, inflammation_base:'low' },
    { id:105, name:'Guisantes (cocidos)',      category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:5.0,  carbs:14.0, fat:0.4,   calories:81,  inflammation_base:'low' },
    { id:106, name:'Habas verdes (cocidas)',   category:'mixed',          quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:7.6,  carbs:19.0, fat:0.4,   calories:110, inflammation_base:'low' },
    // Proteínas animales premium
    { id:107, name:'Pechuga de pato (s/piel)', category:'protein_high',  quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:23.5, carbs:0.0,  fat:5.9,   calories:148, inflammation_base:'low' },
    { id:108, name:'Conejo',                   category:'protein_high',  quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:21.0, carbs:0.0,  fat:5.0,   calories:136, inflammation_base:'low' },
    { id:109, name:'Anchoas (aceite, esc.)',   category:'protein_high',  quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:29.0, carbs:0.0,  fat:10.0,  calories:210, inflammation_base:'low' },
    { id:110, name:'Boquerón fresco',          category:'protein_high',  quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:20.4, carbs:0.0,  fat:4.8,   calories:122, inflammation_base:'low' },
    { id:111, name:'Ternera picada 95%',       category:'protein_high',  quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:21.0, carbs:0.0,  fat:7.0,   calories:152, inflammation_base:'medium' },
    { id:112, name:'Jamón serrano (magro)',    category:'protein_high',  quality:'high',   calorie_density:'medium', satiety_index:'high',   protein:30.0, carbs:0.0,  fat:8.0,   calories:196, inflammation_base:'low' },
    { id:113, name:'Vieiras (cocidas)',        category:'protein_high',  quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:17.0, carbs:3.2,  fat:0.8,   calories:88,  inflammation_base:'low' },
    // Cereales y granos adicionales
    { id:114, name:'Trigo sarraceno (cocido)', category:'carb_high',     quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:3.4,  carbs:19.9, fat:0.6,   calories:92,  inflammation_base:'low' },
    { id:115, name:'Amaranto (cocido)',        category:'carb_high',     quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:3.8,  carbs:18.7, fat:1.6,   calories:102, inflammation_base:'low' },
    { id:116, name:'Teff (cocido)',            category:'carb_high',     quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:3.9,  carbs:22.5, fat:0.7,   calories:101, inflammation_base:'low' },
    { id:117, name:'Espaguetis (cocidos)',     category:'carb_high',     quality:'medium', calorie_density:'low',    satiety_index:'medium', protein:5.8,  carbs:30.9, fat:0.9,   calories:157, inflammation_base:'low' },
    { id:118, name:'Tortita de maíz (wrap)',  category:'carb_medium',   quality:'medium', calorie_density:'medium', satiety_index:'medium', protein:7.3,  carbs:55.0, fat:4.5,   calories:291, inflammation_base:'low' },
    // Frutas adicionales
    { id:119, name:'Pomelo',                  category:'carb_medium',   quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.8,  carbs:11.0, fat:0.2,   calories:42,  inflammation_base:'low' },
    { id:120, name:'Papaya',                  category:'carb_medium',   quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.5,  carbs:11.0, fat:0.3,   calories:43,  inflammation_base:'low' },
    { id:121, name:'Mandarina',               category:'carb_medium',   quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.8,  carbs:13.0, fat:0.3,   calories:53,  inflammation_base:'low' },
    { id:122, name:'Granada (semillas)',      category:'carb_medium',   quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.7,  carbs:19.0, fat:1.2,   calories:83,  inflammation_base:'low' },
    { id:123, name:'Frambuesas',              category:'carb_medium',   quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.2,  carbs:12.0, fat:0.7,   calories:52,  inflammation_base:'low' },
    { id:124, name:'Moras',                   category:'carb_medium',   quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.4,  carbs:10.0, fat:0.5,   calories:43,  inflammation_base:'low' },
    // Lácteos y bebidas vegetales
    { id:125, name:'Leche de avena',          category:'carb_medium',   quality:'medium', calorie_density:'low',    satiety_index:'low',    protein:1.0,  carbs:6.5,  fat:1.5,   calories:45,  inflammation_base:'low' },
    { id:126, name:'Bebida de soja s/azúcar', category:'protein_medium',quality:'high',   calorie_density:'low',    satiety_index:'low',    protein:3.3,  carbs:1.2,  fat:1.8,   calories:36,  inflammation_base:'low' },
    { id:127, name:'Queso fresco batido 0%',  category:'protein_medium',quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:8.0,  carbs:3.6,  fat:0.1,   calories:48,  inflammation_base:'low' },
    { id:128, name:'Yogur natural entero',    category:'protein_medium',quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:3.5,  carbs:4.7,  fat:3.3,   calories:61,  inflammation_base:'low' },
    // Superfoods y potenciadores
    { id:129, name:'Espirulina en polvo',     category:'protein_high',  quality:'high',   calorie_density:'medium', satiety_index:'medium', protein:57.5, carbs:23.9, fat:7.7,   calories:290, inflammation_base:'low' },
    { id:130, name:'Levadura nutricional',    category:'protein_high',  quality:'high',   calorie_density:'medium', satiety_index:'medium', protein:50.0, carbs:31.0, fat:8.0,   calories:325, inflammation_base:'low' },
    { id:131, name:'Semillas de sésamo',      category:'fat_high',      quality:'high',   calorie_density:'high',   satiety_index:'medium', protein:17.7, carbs:23.4, fat:49.7,  calories:573, inflammation_base:'low' },
    { id:132, name:'Anacardos',               category:'fat_high',      quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:18.2, carbs:30.2, fat:43.9,  calories:553, inflammation_base:'low' },
    { id:133, name:'Avellanas',               category:'fat_high',      quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:14.1, carbs:16.7, fat:60.8,  calories:628, inflammation_base:'low' },
    // Verduras adicionales
    { id:134, name:'Espárragos',              category:'mixed',         quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:2.2,  carbs:3.9,  fat:0.1,   calories:20,  inflammation_base:'low' },
    { id:135, name:'Alcachofa (cocida)',      category:'mixed',         quality:'high',   calorie_density:'low',    satiety_index:'high',   protein:3.3,  carbs:10.5, fat:0.2,   calories:53,  inflammation_base:'low' },
    { id:136, name:'Puerro',                  category:'mixed',         quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.5,  carbs:14.2, fat:0.3,   calories:61,  inflammation_base:'low' },
    { id:137, name:'Apio',                    category:'mixed',         quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:0.7,  carbs:3.0,  fat:0.2,   calories:14,  inflammation_base:'low' },
    { id:138, name:'Col lombarda',            category:'mixed',         quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.4,  carbs:7.4,  fat:0.2,   calories:31,  inflammation_base:'low' },
    { id:139, name:'Berros',                  category:'mixed',         quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:2.3,  carbs:1.3,  fat:0.1,   calories:11,  inflammation_base:'low' },
    { id:140, name:'Bok choy',                category:'mixed',         quality:'high',   calorie_density:'low',    satiety_index:'medium', protein:1.5,  carbs:2.2,  fat:0.2,   calories:13,  inflammation_base:'low' },
    // Grasas premium
    { id:141, name:'Aceite de aguacate',      category:'fat_high',      quality:'high',   calorie_density:'high',   satiety_index:'low',    protein:0.0,  carbs:0.0,  fat:100.0, calories:884, inflammation_base:'low' },
    { id:142, name:'Crema de cacahuete 100%', category:'fat_high',      quality:'high',   calorie_density:'high',   satiety_index:'high',   protein:25.8, carbs:21.5, fat:50.4,  calories:614, inflammation_base:'low' },
  ];

  // ── Recetas de élite (nutricionistas de alto rendimiento) ─────────────────
  // Cada receta incluye: escenario, macros por ración, ingredientes con gramos,
  // pasos de preparación y nota de nutricionista con el razonamiento científico.
  const ELITE_RECIPES = [

    // ── PRE-ENTRENO ──────────────────────────────────────────────────────────
    {
      id: 1,
      name: 'Tortitas de avena y clara de huevo',
      emoji: '🥞',
      scenario: ['pre_workout', 'breakfast'],
      difficulty: 'low',
      prep_time: 10,
      servings: 1,
      budget_tier: 'low',
      dietary: ['gluten_free_opt', 'vegetarian'],
      macros: { protein: 38, carbs: 52, fat: 6, calories: 418 },
      ingredients: [
        { item: 'Avena en copos', amount: 80, unit: 'g' },
        { item: 'Clara de huevo', amount: 200, unit: 'g (≈6 claras)' },
        { item: 'Plátano maduro', amount: 60, unit: 'g (½ pieza)' },
        { item: 'Canela molida', amount: 2, unit: 'g' },
        { item: 'Aceite de coco', amount: 5, unit: 'g' },
      ],
      steps: [
        'Tritura la avena hasta obtener harina fina.',
        'Mezcla harina de avena, claras, plátano aplastado y canela hasta obtener masa homogénea.',
        'Calienta una sartén antiadherente con el aceite de coco a fuego medio.',
        'Vierte ¼ de la masa por tortita. Cocina 2-3 min por lado hasta dorar.',
        'Sirve con miel de agave (opcional, +20 kcal) si el entrenamiento dura más de 75 min.',
      ],
      nutritionist_note: 'Los carbohidratos de la avena + plátano elevan el glucógeno muscular disponible en 2-3 h. Las claras aportan aminoácidos de alta biodisponibilidad sin la grasa de la yema, que retrasa el vaciado gástrico y llega tarde al músculo. Comida perfecta 90-120 min antes de entrenar.',
    },
    {
      id: 2,
      name: 'Bowl de arroz blanco y pavo con boniato',
      emoji: '🍚',
      scenario: ['pre_workout', 'bulking'],
      difficulty: 'low',
      prep_time: 20,
      servings: 1,
      budget_tier: 'low',
      dietary: [],
      macros: { protein: 45, carbs: 78, fat: 4, calories: 532 },
      ingredients: [
        { item: 'Arroz blanco (cocido)', amount: 200, unit: 'g' },
        { item: 'Pechuga de pavo', amount: 150, unit: 'g' },
        { item: 'Boniato (cocido)', amount: 100, unit: 'g' },
        { item: 'Sal y especias al gusto', amount: null, unit: null },
        { item: 'Aceite de oliva AOVE', amount: 5, unit: 'g' },
      ],
      steps: [
        'Cocina el arroz blanco y el boniato al vapor o en agua con sal.',
        'Cocina la pechuga de pavo a la plancha con especias (cúrcuma + pimienta).',
        'Corta el pavo en dados. Mezcla con arroz y boniato.',
        'Aliña con el AOVE. Sirve templado.',
      ],
      nutritionist_note: 'El arroz blanco (índice glucémico alto) es preferible al integral antes de entrenar: se digiere más rápido y libera glucosa al torrente sanguíneo cuando el músculo la necesita. El boniato añade potasio (vital para la contracción muscular) y carbohidratos de absorción moderada para mantener el glucógeno estable durante sesiones largas.',
    },
    {
      id: 3,
      name: 'Pancakes de plátano y proteína',
      emoji: '🍌',
      scenario: ['pre_workout', 'breakfast'],
      difficulty: 'low',
      prep_time: 8,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['gluten_free', 'dairy_free'],
      macros: { protein: 42, carbs: 58, fat: 7, calories: 471 },
      ingredients: [
        { item: 'Plátano maduro', amount: 120, unit: 'g (1 pieza grande)' },
        { item: 'Huevo entero', amount: 100, unit: 'g (2 huevos)' },
        { item: 'Proteína whey vainilla', amount: 30, unit: 'g (1 scoop)' },
        { item: 'Canela', amount: 2, unit: 'g' },
        { item: 'Aceite de coco', amount: 5, unit: 'g' },
      ],
      steps: [
        'Aplasta el plátano con un tenedor hasta textura de puré.',
        'Añade los huevos, el scoop de whey y la canela. Mezcla bien.',
        'Calienta la sartén con aceite de coco a fuego medio-bajo.',
        'Cocina pancakes pequeños (8-10 cm) 2 min por lado. Fuego bajo para que no quemen.',
        'Sirve con frutos rojos frescos o mermelada sin azúcar.',
      ],
      nutritionist_note: 'Esta receta sin harina elimina el pico de insulina brusco. El plátano maduro proporciona glucosa + fructosa en ratio 1:1, que recarga el glucógeno hepático Y muscular de forma simultánea. Ideal 60-90 min antes de entrenar. El whey añade BCAAs que reducen el catabolismo durante el entrenamiento en ayunas.',
    },

    // ── POST-ENTRENO ─────────────────────────────────────────────────────────
    {
      id: 4,
      name: 'Rice bowl del campeón (pollo + arroz + verduras)',
      emoji: '🏆',
      scenario: ['post_workout', 'bulking'],
      difficulty: 'low',
      prep_time: 25,
      servings: 1,
      budget_tier: 'low',
      dietary: [],
      macros: { protein: 55, carbs: 80, fat: 8, calories: 620 },
      ingredients: [
        { item: 'Pechuga de pollo', amount: 180, unit: 'g' },
        { item: 'Arroz blanco (cocido)', amount: 250, unit: 'g' },
        { item: 'Brócoli', amount: 100, unit: 'g' },
        { item: 'Zanahoria', amount: 80, unit: 'g' },
        { item: 'Salsa de soja baja en sodio', amount: 15, unit: 'ml' },
        { item: 'Aceite de sésamo', amount: 5, unit: 'g' },
      ],
      steps: [
        'Cocina el pollo a la plancha y córtalo en tiras.',
        'Saltea brócoli y zanahoria en 3 min con un poco de agua al vapor.',
        'Mezcla arroz, pollo y verduras en un bol.',
        'Aliña con salsa de soja y aceite de sésamo.',
        'Consume dentro de los primeros 60 min post-entreno.',
      ],
      nutritionist_note: 'Ratio proteína:carbohidratos 1:1.5, el rango óptimo post-entreno según meta-análisis de Ivy & Schoenfeld. El arroz blanco rehidrata el glucógeno muscular agotado. La leucina del pollo activa el mTORC1 (interruptor de la síntesis proteica). Añade 5 g de creatina en este momento para máxima absorción celular.',
    },
    {
      id: 5,
      name: 'Smoothie post-entreno de recuperación rápida',
      emoji: '🥤',
      scenario: ['post_workout'],
      difficulty: 'low',
      prep_time: 5,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['vegetarian', 'gluten_free'],
      macros: { protein: 45, carbs: 62, fat: 4, calories: 464 },
      ingredients: [
        { item: 'Proteína whey', amount: 40, unit: 'g (1.3 scoops)' },
        { item: 'Plátano congelado', amount: 120, unit: 'g' },
        { item: 'Leche desnatada', amount: 300, unit: 'ml' },
        { item: 'Miel pura', amount: 15, unit: 'g' },
        { item: 'Cacao puro en polvo', amount: 10, unit: 'g' },
        { item: 'Hielo', amount: 100, unit: 'g' },
      ],
      steps: [
        'Introduce todos los ingredientes en la batidora.',
        'Tritura a máxima potencia durante 45 segundos.',
        'Sirve y consume de inmediato (no guardar — la whey degrada rápido en líquido).',
      ],
      nutritionist_note: 'Diseñado para consumir en los 30 min post-entreno cuando no hay tiempo para cocinar. La whey tiene el mayor perfil de aminoácidos esenciales y la mayor velocidad de absorción (pico en sangre a los 60-90 min). El plátano + miel reponen el glucógeno rápidamente. El cacao aporta teobromina (antiinflamatorio) y antioxidantes que reducen el daño muscular.',
    },
    {
      id: 6,
      name: 'Pasta de legumbre con atún y pesto',
      emoji: '🍝',
      scenario: ['post_workout', 'carb_loading'],
      difficulty: 'low',
      prep_time: 15,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['dairy_free'],
      macros: { protein: 52, carbs: 75, fat: 12, calories: 620 },
      ingredients: [
        { item: 'Pasta de legumbre (garbanzos o lentejas)', amount: 80, unit: 'g (seco)' },
        { item: 'Atún en agua (escurrido)', amount: 160, unit: 'g (2 latas)' },
        { item: 'Pesto de albahaca', amount: 20, unit: 'g' },
        { item: 'Tomates cherry', amount: 80, unit: 'g' },
        { item: 'Aceite de oliva AOVE', amount: 5, unit: 'g' },
        { item: 'Sal, pimienta, orégano', amount: null, unit: null },
      ],
      steps: [
        'Cuece la pasta según instrucciones del paquete (7-9 min). Escurre.',
        'Mezcla pasta caliente con pesto mientras drena.',
        'Añade atún desmenuzado y tomates cherry cortados.',
        'Aliña con AOVE, sal y orégano.',
      ],
      nutritionist_note: 'La pasta de legumbre tiene el doble de proteína que la pasta de trigo y una carga glucémica más baja, pero con más carbohidratos totales que el arroz. Perfecta para carga de carbohidratos el día antes de competición o para reponer glucógeno tras sesiones de alta intensidad (>90 min). El atún aporta omega-3 que reduce el DOMS (dolor muscular post-entreno).',
    },

    // ── CUTTING / DÉFICIT CALÓRICO ────────────────────────────────────────────
    {
      id: 7,
      name: 'Ensalada de atún, edamame y aguacate',
      emoji: '🥗',
      scenario: ['cutting', 'lunch'],
      difficulty: 'low',
      prep_time: 10,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['gluten_free', 'dairy_free'],
      macros: { protein: 48, carbs: 18, fat: 18, calories: 422 },
      ingredients: [
        { item: 'Atún en agua (escurrido)', amount: 160, unit: 'g (2 latas)' },
        { item: 'Edamame (cocido)', amount: 100, unit: 'g' },
        { item: 'Aguacate', amount: 80, unit: 'g (½ pieza)' },
        { item: 'Lechuga romana', amount: 150, unit: 'g' },
        { item: 'Tomate cherry', amount: 80, unit: 'g' },
        { item: 'Limón (zumo)', amount: 20, unit: 'ml' },
        { item: 'Aceite de oliva AOVE', amount: 10, unit: 'g' },
      ],
      steps: [
        'Lava y trocea la lechuga. Corta los tomates por la mitad.',
        'Saca el aguacate y córtalo en dados.',
        'Mezcla todos los ingredientes en un bol amplio.',
        'Aliña con AOVE + zumo de limón, sal y pimienta.',
        'El edamame debe estar templado para mejor palatabilidad.',
      ],
      nutritionist_note: 'Alto volumen (plato grande y saciante) con solo 422 kcal. El aguacate aporta ácido oleico que activa la hormona de saciedad CCK. El edamame completa el perfil de aminoácidos del atún (que carece de ciertos BCAAs). La fibra de la lechuga + aguacate retrasa el vaciado gástrico 2-3 h, eliminando el hambre en déficit sin recurrir a más calorías.',
    },
    {
      id: 8,
      name: 'Tortilla de claras con espinacas y queso fresco',
      emoji: '🍳',
      scenario: ['cutting', 'breakfast', 'lunch'],
      difficulty: 'low',
      prep_time: 8,
      servings: 1,
      budget_tier: 'low',
      dietary: ['gluten_free', 'vegetarian'],
      macros: { protein: 40, carbs: 6, fat: 8, calories: 256 },
      ingredients: [
        { item: 'Clara de huevo', amount: 250, unit: 'g (≈7 claras)' },
        { item: 'Espinacas frescas', amount: 80, unit: 'g' },
        { item: 'Queso fresco batido 0%', amount: 60, unit: 'g' },
        { item: 'Cebollino fresco', amount: 10, unit: 'g' },
        { item: 'Sal, pimienta, ajo en polvo', amount: null, unit: null },
        { item: 'Aceite de oliva (spray)', amount: 3, unit: 'g' },
      ],
      steps: [
        'Bate las claras con sal, pimienta y ajo en polvo.',
        'Saltea las espinacas 1 min en sartén antiadherente con spray de aceite.',
        'Vierte las claras sobre las espinacas. Cocina a fuego medio.',
        'Cuando cuaje por los bordes, añade el queso fresco y el cebollino en el centro.',
        'Dobla la tortilla. Sirve inmediatamente.',
      ],
      nutritionist_note: 'Solo 256 kcal con 40 g de proteína — ratio proteína:caloría excepcional para cutting. Las claras son la fuente proteica más pura (90% proteína en sólidos). El queso fresco 0% añade caseína, que sacia más que la whey. Las espinacas aportan hierro y magnesio, micronutrientes que se agotan en déficit calórico prolongado.',
    },
    {
      id: 9,
      name: 'Wok de gambas, brócoli y jengibre',
      emoji: '🍤',
      scenario: ['cutting', 'dinner'],
      difficulty: 'medium',
      prep_time: 15,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['gluten_free', 'dairy_free'],
      macros: { protein: 44, carbs: 20, fat: 8, calories: 328 },
      ingredients: [
        { item: 'Gambas peladas', amount: 200, unit: 'g' },
        { item: 'Brócoli', amount: 200, unit: 'g' },
        { item: 'Pimiento rojo', amount: 80, unit: 'g' },
        { item: 'Jengibre fresco', amount: 10, unit: 'g' },
        { item: 'Salsa de soja baja en sodio', amount: 15, unit: 'ml' },
        { item: 'Aceite de sésamo', amount: 8, unit: 'g' },
        { item: 'Ajo (2 dientes)', amount: 6, unit: 'g' },
      ],
      steps: [
        'Ralla el jengibre y pica el ajo finamente.',
        'Calienta el wok a fuego muy alto. Añade el aceite de sésamo.',
        'Saltea ajo y jengibre 30 s. Añade el pimiento cortado en tiras.',
        'Incorpora el brócoli en ramilletes. Saltea 3 min a fuego alto.',
        'Añade las gambas. Cocina 2-3 min hasta que estén rosadas.',
        'Vierte la salsa de soja. Mezcla y sirve inmediatamente.',
      ],
      nutritionist_note: 'Las gambas tienen el mejor ratio proteína:caloría de todas las proteínas animales (44 g proteína con solo 328 kcal totales). El jengibre tiene efectos antiinflamatorios demostrados (reduce el DOMS post-entreno). El brócoli aporta sulforafano, que activa las vías de detoxificación hepática y mejora el metabolismo hormonal. Cena ideal en cutting: saciante, antiinflamatoria y con mínimas calorías.',
    },
    {
      id: 10,
      name: 'Batido verde proteico (cutting o desayuno)',
      emoji: '🥬',
      scenario: ['cutting', 'breakfast'],
      difficulty: 'low',
      prep_time: 5,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['vegan', 'gluten_free', 'dairy_free'],
      macros: { protein: 38, carbs: 28, fat: 5, calories: 309 },
      ingredients: [
        { item: 'Espinacas frescas', amount: 60, unit: 'g' },
        { item: 'Proteína vegana (guisante)', amount: 30, unit: 'g (1 scoop)' },
        { item: 'Plátano congelado', amount: 80, unit: 'g (½ pieza)' },
        { item: 'Bebida de soja sin azúcar', amount: 250, unit: 'ml' },
        { item: 'Jengibre fresco', amount: 5, unit: 'g' },
        { item: 'Semillas de chía', amount: 10, unit: 'g' },
      ],
      steps: [
        'Introduce todos los ingredientes en la batidora de vaso.',
        'Tritura a máxima potencia 60 s.',
        'Sirve con hielo. Consumir en 15-20 min (la chía espesa el batido).',
      ],
      nutritionist_note: 'Bajo en calorías pero alto en micronutrientes. Las espinacas aportan nitratos que mejoran la eficiencia muscular. Las semillas de chía (10 g) dan 2 g de omega-3 ALA y 3,4 g de fibra que absorben agua y crean sensación de saciedad durante 3-4 h. La proteína de guisante tiene el aminograma más completo de las proteínas vegetales, con alta concentración de arginina que mejora el flujo sanguíneo.',
    },

    // ── BULK / SUPERÁVIT ─────────────────────────────────────────────────────
    {
      id: 11,
      name: 'Steak de ternera con patata al horno',
      emoji: '🥩',
      scenario: ['bulking', 'post_workout'],
      difficulty: 'low',
      prep_time: 35,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['gluten_free', 'dairy_free'],
      macros: { protein: 58, carbs: 65, fat: 18, calories: 650 },
      ingredients: [
        { item: 'Entrecot de ternera (o solomillo)', amount: 200, unit: 'g' },
        { item: 'Patata (sin pelar)', amount: 280, unit: 'g' },
        { item: 'Aceite de oliva AOVE', amount: 15, unit: 'g' },
        { item: 'Romero fresco', amount: 5, unit: 'g' },
        { item: 'Ajo (3 dientes)', amount: 9, unit: 'g' },
        { item: 'Sal gruesa y pimienta negra', amount: null, unit: null },
      ],
      steps: [
        'Precalienta el horno a 200°C. Corta la patata en gajos.',
        'Mezcla los gajos con AOVE, ajo laminado, romero, sal. Hornea 25-30 min.',
        'Saca la carne de la nevera 15 min antes. Salpimienta generosamente.',
        'Marca el steak en sartén de hierro muy caliente: 2-3 min por lado (término medio).',
        'Deja reposar la carne 5 min antes de cortar. Sirve con los gajos.',
      ],
      nutritionist_note: 'La ternera tiene creatina natural (4-5 g/kg de carne), hierro hem de alta biodisponibilidad y zinc, los tres nutrientes más deficitarios en atletas de fuerza. La patata con piel aporta almidón resistente que alimenta el microbioma intestinal y reduce la inflamación sistémica. La combinación proteína completa + carbohidrato de alta densidad es la receta clásica de los preparadores de fuerza.',
    },
    {
      id: 12,
      name: 'Salmón al horno con quinoa y espárragos',
      emoji: '🐟',
      scenario: ['bulking', 'omega3', 'dinner'],
      difficulty: 'medium',
      prep_time: 30,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['gluten_free', 'dairy_free'],
      macros: { protein: 52, carbs: 55, fat: 22, calories: 634 },
      ingredients: [
        { item: 'Lomo de salmón (sin piel)', amount: 180, unit: 'g' },
        { item: 'Quinoa (cocida)', amount: 200, unit: 'g' },
        { item: 'Espárragos verdes', amount: 150, unit: 'g' },
        { item: 'Limón (zumo y ralladura)', amount: 30, unit: 'ml' },
        { item: 'Aceite de oliva AOVE', amount: 10, unit: 'g' },
        { item: 'Eneldo seco', amount: 3, unit: 'g' },
      ],
      steps: [
        'Precalienta el horno a 180°C.',
        'Coloca el salmón en papel de horno. Aliña con zumo y ralladura de limón, eneldo, AOVE.',
        'Hornea 18-20 min (el salmón debe quedar rosado en el centro).',
        'Mientras tanto, saltea los espárragos 5 min.',
        'Sirve sobre la quinoa con los espárragos.',
      ],
      nutritionist_note: 'El salmón aporta 3,5 g de EPA+DHA en una sola ración, la dosis terapéutica para reducir la inflamación muscular y mejorar la sensibilidad a la insulina. La quinoa es la única fuente vegetal con proteína completa (todos los aminoácidos esenciales) y tiene ecdisona, un compuesto que estudios recientes asocian con mayor síntesis proteica.',
    },
    {
      id: 13,
      name: 'Pollo teriyaki con arroz y edamame',
      emoji: '🍗',
      scenario: ['bulking', 'meal_prep'],
      difficulty: 'medium',
      prep_time: 25,
      servings: 2,
      budget_tier: 'low',
      dietary: ['dairy_free'],
      macros: { protein: 52, carbs: 72, fat: 8, calories: 572 },
      ingredients: [
        { item: 'Muslo de pollo sin piel', amount: 200, unit: 'g (por ración)' },
        { item: 'Arroz blanco (cocido)', amount: 200, unit: 'g (por ración)' },
        { item: 'Edamame (cocido)', amount: 80, unit: 'g (por ración)' },
        { item: 'Salsa de soja baja en sodio', amount: 30, unit: 'ml (total)' },
        { item: 'Miel', amount: 15, unit: 'g (total)' },
        { item: 'Ajo en polvo', amount: 3, unit: 'g' },
        { item: 'Jengibre en polvo', amount: 2, unit: 'g' },
      ],
      steps: [
        'Mezcla salsa de soja, miel, ajo y jengibre para el teriyaki.',
        'Marina el pollo 20 min en la salsa.',
        'Cocina el pollo en sartén a fuego medio 5-6 min por lado.',
        'Reduce el resto de la salsa 2 min para glasear.',
        'Sirve sobre el arroz con el edamame. Glasea con la salsa reducida.',
      ],
      nutritionist_note: 'El muslo de pollo tiene un 20% más de grasa que la pechuga, pero aporta más ácidos grasos monoinsaturados y mejor palatabilidad — clave para mantener el superávit calórico sin que el eating se vuelva una tarea. El edamame completa los aminoácidos del arroz. Esta receta se prepara bien para meal prep de 3-4 días (refrigerar en tuppers).',
    },

    // ── VEGAN / VEGETAL ──────────────────────────────────────────────────────
    {
      id: 14,
      name: 'Bowl de tofu firme, quinoa y kale',
      emoji: '🫘',
      scenario: ['vegan', 'post_workout', 'bulking'],
      difficulty: 'medium',
      prep_time: 20,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['vegan', 'gluten_free', 'dairy_free'],
      macros: { protein: 42, carbs: 58, fat: 14, calories: 538 },
      ingredients: [
        { item: 'Tofu firme', amount: 200, unit: 'g' },
        { item: 'Quinoa (cocida)', amount: 150, unit: 'g' },
        { item: 'Kale (col rizada)', amount: 80, unit: 'g' },
        { item: 'Remolacha (cocida)', amount: 80, unit: 'g' },
        { item: 'Semillas de cáñamo', amount: 15, unit: 'g' },
        { item: 'Tahini', amount: 20, unit: 'g' },
        { item: 'Limón (zumo)', amount: 15, unit: 'ml' },
        { item: 'Salsa de soja y ajo en polvo', amount: null, unit: null },
      ],
      steps: [
        'Escurre y prensa el tofu para eliminar el exceso de agua (30 min con peso encima).',
        'Corta el tofu en dados y saltea con salsa de soja y ajo en polvo hasta dorar.',
        'Masajea el kale con aceite y sal para ablandarlo.',
        'Prepara el aderezo: tahini + zumo de limón + 20 ml agua + sal.',
        'Monta el bowl: quinoa, kale, remolacha en dados, tofu y semillas de cáñamo.',
        'Vierte el aderezo de tahini.',
      ],
      nutritionist_note: 'El combo quinoa + tofu + semillas de cáñamo produce un perfil completo de aminoácidos esenciales. Las semillas de cáñamo tienen ratio omega-3:omega-6 óptimo (1:3) y 32 g de proteína por 100 g. La remolacha aporta nitratos que mejoran la eficiencia del VO2max en un 3-5%. La fermentación del tofu (cuando se usa tempeh) aumenta la biodisponibilidad del zinc y el hierro en proteínas vegetales.',
    },
    {
      id: 15,
      name: 'Tempeh salteado con arroz integral y brócoli',
      emoji: '🌱',
      scenario: ['vegan', 'bulking', 'meal_prep'],
      difficulty: 'medium',
      prep_time: 25,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['vegan', 'dairy_free'],
      macros: { protein: 44, carbs: 62, fat: 16, calories: 572 },
      ingredients: [
        { item: 'Tempeh', amount: 180, unit: 'g' },
        { item: 'Arroz integral (cocido)', amount: 200, unit: 'g' },
        { item: 'Brócoli', amount: 150, unit: 'g' },
        { item: 'Salsa de soja baja en sodio', amount: 20, unit: 'ml' },
        { item: 'Aceite de sésamo', amount: 8, unit: 'g' },
        { item: 'Cúrcuma + pimienta negra', amount: 3, unit: 'g' },
        { item: 'Ajo (2 dientes)', amount: 6, unit: 'g' },
      ],
      steps: [
        'Corta el tempeh en dados de 1-2 cm.',
        'Calienta el aceite de sésamo. Saltea el ajo 30 s.',
        'Añade el tempeh. Dora 4-5 min hasta que esté crujiente.',
        'Incorpora el brócoli y la cúrcuma + pimienta negra.',
        'Añade la salsa de soja y 30 ml de agua. Cocina 3 min más.',
        'Sirve sobre el arroz integral.',
      ],
      nutritionist_note: 'El tempeh tiene la biodisponibilidad más alta de las proteínas vegetales gracias al proceso de fermentación, que predigiere los fitatos que bloquean la absorción de zinc y hierro. La pimienta negra (piperina) aumenta la absorción de la cúrcuma en un 2000%. El arroz integral tiene más zinc y magnesio que el blanco, cruciales para la síntesis de testosterona en atletas veganos.',
    },
    {
      id: 16,
      name: 'Sopa de lentejas rojas y coco (vegan + budget)',
      emoji: '🍲',
      scenario: ['vegan', 'budget', 'cutting', 'meal_prep'],
      difficulty: 'low',
      prep_time: 25,
      servings: 3,
      budget_tier: 'low',
      dietary: ['vegan', 'gluten_free', 'dairy_free'],
      macros: { protein: 26, carbs: 48, fat: 9, calories: 381 },
      ingredients: [
        { item: 'Lentejas rojas', amount: 200, unit: 'g (seco)' },
        { item: 'Leche de coco ligera', amount: 200, unit: 'ml' },
        { item: 'Caldo de verduras', amount: 800, unit: 'ml' },
        { item: 'Tomate triturado', amount: 200, unit: 'g' },
        { item: 'Cebolla', amount: 100, unit: 'g' },
        { item: 'Ajo (3 dientes)', amount: 9, unit: 'g' },
        { item: 'Curry + cúrcuma + comino', amount: 8, unit: 'g (total)' },
        { item: 'Espinacas frescas', amount: 60, unit: 'g' },
      ],
      steps: [
        'Sofríe cebolla y ajo a fuego medio 5 min.',
        'Añade las especias. Tuéstalas 1 min (activa sus compuestos activos).',
        'Incorpora las lentejas, tomate, caldo y leche de coco.',
        'Cocina a fuego medio 20-25 min hasta que las lentejas estén tiernas.',
        'Añade las espinacas en el último minuto. Tritura ½ la sopa si prefieres textura cremosa.',
      ],
      nutritionist_note: 'Coste de €0.60-0.80 por ración con 26 g de proteína y alta saciedad gracias a la fibra soluble de las lentejas (12 g/ración). La leche de coco aporta MCTs que se metabolizan directamente como energía sin almacenarse como grasa. Las lentejas rojas no necesitan remojo y se cocinan en 20 min, siendo las más prácticas para meal prep semanal.',
    },

    // ── ANTES DE DORMIR / RECUPERACIÓN NOCTURNA ──────────────────────────────
    {
      id: 17,
      name: 'Pudding de caseína nocturno',
      emoji: '🌙',
      scenario: ['before_sleep', 'cutting'],
      difficulty: 'low',
      prep_time: 5,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['gluten_free', 'vegetarian'],
      macros: { protein: 42, carbs: 18, fat: 4, calories: 276 },
      ingredients: [
        { item: 'Caseína en polvo (chocolate o vainilla)', amount: 40, unit: 'g' },
        { item: 'Yogur griego 0%', amount: 150, unit: 'g' },
        { item: 'Leche desnatada', amount: 60, unit: 'ml' },
        { item: 'Cacao puro en polvo', amount: 8, unit: 'g' },
        { item: 'Frutos rojos', amount: 50, unit: 'g' },
      ],
      steps: [
        'Mezcla la caseína con el yogur griego y el cacao.',
        'Añade la leche poco a poco hasta conseguir textura de pudding (espeso).',
        'Refrigera 15-20 min para que espese más.',
        'Sirve con los frutos rojos encima.',
        'Consumir 30-60 min antes de dormir.',
      ],
      nutritionist_note: 'La caseína es la proteína de digestión más lenta (6-8 h vs 1-2 h de la whey). Libera aminoácidos de forma sostenida durante toda la noche, cuando los niveles de GH son máximos (fases 3-4 del sueño). Estudio de Res et al. (2012) en J Nutrition: 40 g de caseína nocturna aumentaron la síntesis proteica muscular nocturna en un 22%. Es la única suplementación proteica realmente importante ANTES de dormir.',
    },
    {
      id: 18,
      name: 'Bowl de requesón con frutos rojos y nueces',
      emoji: '🫐',
      scenario: ['before_sleep', 'cutting', 'snack'],
      difficulty: 'low',
      prep_time: 3,
      servings: 1,
      budget_tier: 'low',
      dietary: ['gluten_free', 'vegetarian'],
      macros: { protein: 30, carbs: 22, fat: 14, calories: 334 },
      ingredients: [
        { item: 'Requesón (o cottage cheese)', amount: 200, unit: 'g' },
        { item: 'Frutos rojos mix (arándanos, frambuesas)', amount: 80, unit: 'g' },
        { item: 'Nueces', amount: 20, unit: 'g' },
        { item: 'Canela molida', amount: 2, unit: 'g' },
        { item: 'Extracto de vainilla', amount: 2, unit: 'ml' },
      ],
      steps: [
        'Coloca el requesón en un bol.',
        'Añade los frutos rojos, nueces y canela.',
        'Mezcla ligeramente. No hace falta añadir edulcorantes.',
      ],
      nutritionist_note: 'El requesón es 85% caseína micelar — la forma de caseína más lenta y efectiva para la síntesis nocturna. Los arándanos contienen antocianinas que reducen el estrés oxidativo muscular durante el sueño. Las nueces aportan melatonina natural y omega-3 ALA que potencia la calidad del sueño. Snack perfecto antes de dormir con solo 334 kcal.',
    },
    {
      id: 19,
      name: 'Mousse de chocolate y caseína (antojo nocturno)',
      emoji: '🍫',
      scenario: ['before_sleep', 'snack', 'cutting'],
      difficulty: 'low',
      prep_time: 10,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['gluten_free', 'vegetarian'],
      macros: { protein: 38, carbs: 14, fat: 6, calories: 266 },
      ingredients: [
        { item: 'Caseína sabor chocolate', amount: 35, unit: 'g' },
        { item: 'Queso fresco batido 0%', amount: 100, unit: 'g' },
        { item: 'Cacao puro en polvo', amount: 10, unit: 'g' },
        { item: 'Leche desnatada (fría)', amount: 40, unit: 'ml' },
        { item: 'Edulcorante (opcional)', amount: null, unit: null },
      ],
      steps: [
        'Mezcla caseína, queso fresco, cacao y leche con varillas o batidora de mano.',
        'Bate enérgicamente 2-3 min hasta que doble su volumen (efecto mousse).',
        'Refrigera 20-30 min para que tome textura firme.',
        'Sirve frío. Dura 24 h en nevera.',
      ],
      nutritionist_note: 'Diseñado para eliminar el antojo de chocolate sin salirse del déficit calórico. La palatabilidad alta reduce el riesgo de abandono del plan en semanas 4-6 de cutting, cuando la adherencia es el mayor problema. 266 kcal con 38 g de proteína de liberación lenta. Truco: usar leche muy fría y batir con fuerza para el efecto mousse sin nata ni azúcar.',
    },

    // ── DESAYUNO DEPORTIVO ────────────────────────────────────────────────────
    {
      id: 20,
      name: 'Overnight oats proteicos (preparación la noche anterior)',
      emoji: '🌙',
      scenario: ['breakfast', 'meal_prep', 'pre_workout'],
      difficulty: 'low',
      prep_time: 5,
      servings: 1,
      budget_tier: 'low',
      dietary: ['gluten_free_opt', 'vegetarian'],
      macros: { protein: 36, carbs: 60, fat: 8, calories: 464 },
      ingredients: [
        { item: 'Avena en copos', amount: 70, unit: 'g' },
        { item: 'Proteína whey', amount: 25, unit: 'g (1 scoop pequeño)' },
        { item: 'Leche desnatada', amount: 200, unit: 'ml' },
        { item: 'Yogur griego 0%', amount: 80, unit: 'g' },
        { item: 'Semillas de chía', amount: 10, unit: 'g' },
        { item: 'Frutos rojos congelados', amount: 60, unit: 'g' },
        { item: 'Miel', amount: 10, unit: 'g' },
      ],
      steps: [
        'Mezcla todos los ingredientes en un frasco de cristal o tupperware.',
        'Deja los frutos rojos congelados en la parte superior.',
        'Tapa y refrigera toda la noche (mínimo 6 h).',
        'Por la mañana, mezcla y come frío directamente.',
      ],
      nutritionist_note: 'La avena remojada tiene mayor biodisponibilidad de almidón que la cocida, con menor respuesta glucémica. El almidón resistente que se forma durante el remojo alimenta el microbioma intestinal, que a su vez produce ácidos grasos de cadena corta que mejoran la sensibilidad a la insulina. Perfecto para preparar el domingo y tener desayunos listos los 5 días de la semana.',
    },
    {
      id: 21,
      name: 'Revuelto de huevo y salmón ahumado',
      emoji: '🍳',
      scenario: ['breakfast', 'post_workout'],
      difficulty: 'low',
      prep_time: 10,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['gluten_free', 'dairy_free'],
      macros: { protein: 42, carbs: 4, fat: 22, calories: 390 },
      ingredients: [
        { item: 'Huevo entero', amount: 150, unit: 'g (3 huevos)' },
        { item: 'Salmón ahumado', amount: 80, unit: 'g' },
        { item: 'Aguacate', amount: 60, unit: 'g' },
        { item: 'Cebollino', amount: 10, unit: 'g' },
        { item: 'Aceite de oliva (spray)', amount: 3, unit: 'g' },
        { item: 'Pimienta negra y eneldo', amount: null, unit: null },
      ],
      steps: [
        'Bate los huevos con pimienta y eneldo.',
        'Cocina el revuelto a fuego muy bajo, moviendo constantemente.',
        'Cuando esté casi cuajado (cremoso), retira del fuego.',
        'Sirve con el salmón en tiras, aguacate en dados y cebollino.',
      ],
      nutritionist_note: 'Los huevos enteros contienen colesterol dietético que no eleva el colesterol plasmático en la mayoría de personas (refutado en meta-análisis de Fernandez, 2006). La yema aporta colina (esencial para la función cognitiva y la síntesis de acetilcolina) y luteína. El salmón ahumado suma 1,5 g de EPA+DHA en una ración. Desayuno cetogénico con alta saciedad.',
    },
    {
      id: 22,
      name: 'Bowl de quinoa, plátano y mantequilla de almendra',
      emoji: '🥣',
      scenario: ['breakfast', 'pre_workout', 'vegan'],
      difficulty: 'low',
      prep_time: 10,
      servings: 1,
      budget_tier: 'medium',
      dietary: ['vegan', 'gluten_free', 'dairy_free'],
      macros: { protein: 22, carbs: 68, fat: 16, calories: 508 },
      ingredients: [
        { item: 'Quinoa (cocida)', amount: 150, unit: 'g' },
        { item: 'Plátano', amount: 100, unit: 'g (1 pieza pequeña)' },
        { item: 'Mantequilla de almendra 100%', amount: 25, unit: 'g' },
        { item: 'Bebida de soja sin azúcar', amount: 60, unit: 'ml' },
        { item: 'Canela', amount: 2, unit: 'g' },
        { item: 'Semillas de granada (opcional)', amount: 20, unit: 'g' },
      ],
      steps: [
        'Calienta la quinoa con la bebida de soja 2 min en microondas.',
        'Añade la mantequilla de almendra y mezcla bien.',
        'Trocea el plátano. Coloca encima de la quinoa.',
        'Espolvorea canela y semillas de granada.',
      ],
      nutritionist_note: 'Desayuno plant-based ideal cuando el entrenamiento es en 90-120 min. La quinoa es el único cereal con los 9 aminoácidos esenciales. La mantequilla de almendra aporta vitamina E (el antioxidante más importante para la membrana de la célula muscular) y magnesio. El plátano da un aporte rápido de carbohidratos para el entrenamiento matutino.',
    },

    // ── ECONÓMICO / BUDGET ────────────────────────────────────────────────────
    {
      id: 23,
      name: 'Bowl de arroz, huevo y legumbres (€1 la ración)',
      emoji: '💰',
      scenario: ['budget', 'bulking', 'meal_prep'],
      difficulty: 'low',
      prep_time: 20,
      servings: 2,
      budget_tier: 'low',
      dietary: ['vegetarian', 'gluten_free', 'dairy_free'],
      macros: { protein: 32, carbs: 70, fat: 8, calories: 480 },
      ingredients: [
        { item: 'Arroz blanco', amount: 90, unit: 'g (seco, por ración)' },
        { item: 'Huevo entero', amount: 150, unit: 'g (3 huevos, por ración)' },
        { item: 'Garbanzos en conserva (escurridos)', amount: 120, unit: 'g (por ración)' },
        { item: 'Espinacas congeladas', amount: 80, unit: 'g (por ración)' },
        { item: 'Aceite de oliva', amount: 10, unit: 'g (por ración)' },
        { item: 'Sal, pimentón, cúrcuma', amount: null, unit: null },
      ],
      steps: [
        'Cuece el arroz con sal y cúrcuma (da color y antiinflamatorio).',
        'Descongela las espinacas en sartén con aceite y ajo.',
        'Añade los garbanzos escurridos. Cocina 3 min.',
        'Haz un hueco en la mezcla. Casca los 3 huevos directamente.',
        'Cubre y deja cuajar 3-4 min. Sirve sobre el arroz.',
      ],
      nutritionist_note: 'Coste estimado: €0.80-1.10 por ración con 32 g de proteína completa. Los garbanzos + arroz forman una proteína complementaria perfecta (el arroz tiene metionina que falta en las legumbres; las legumbres tienen lisina que falta en los cereales). Las espinacas congeladas tienen el mismo valor nutricional que las frescas — a veces más, porque se congelan en el momento óptimo de maduración.',
    },
    {
      id: 24,
      name: 'Cazuela de pavo picado, boniato y espinacas',
      emoji: '🥘',
      scenario: ['budget', 'bulking', 'meal_prep', 'post_workout'],
      difficulty: 'low',
      prep_time: 30,
      servings: 3,
      budget_tier: 'low',
      dietary: ['gluten_free', 'dairy_free'],
      macros: { protein: 46, carbs: 40, fat: 8, calories: 420 },
      ingredients: [
        { item: 'Pavo picado (magro)', amount: 200, unit: 'g (por ración)' },
        { item: 'Boniato', amount: 150, unit: 'g (por ración)' },
        { item: 'Espinacas frescas', amount: 80, unit: 'g (por ración)' },
        { item: 'Tomate triturado', amount: 100, unit: 'g (por ración)' },
        { item: 'Cebolla', amount: 50, unit: 'g (total)' },
        { item: 'Aceite de oliva', amount: 8, unit: 'g (por ración)' },
        { item: 'Comino, orégano, sal', amount: null, unit: null },
      ],
      steps: [
        'Corta el boniato en dados de 2 cm. Saltea con cebolla 5 min.',
        'Añade el pavo picado. Desmenuza y dora bien (5-7 min).',
        'Incorpora el tomate triturado y las especias.',
        'Cocina a fuego medio 10 min hasta que el boniato esté tierno.',
        'Añade las espinacas en el último minuto. Sirve.',
      ],
      nutritionist_note: 'Receta diseñada para meal prep masivo: se prepara en 30 min para 3 raciones y aguanta 4 días en nevera o 2 meses congelada. El pavo picado es más económico que la pechuga y tiene más grasa saludable. El boniato aporta beta-caroteno (precursor de vitamina A, esencial para la recuperación de tejidos) y su índice glucémico moderado evita picos de insulina.',
    },

    // ── MEAL PREP ────────────────────────────────────────────────────────────
    {
      id: 25,
      name: 'Chicken bowl de quinoa (meal prep 5 días)',
      emoji: '📦',
      scenario: ['meal_prep', 'bulking', 'post_workout'],
      difficulty: 'medium',
      prep_time: 45,
      servings: 5,
      budget_tier: 'low',
      dietary: ['gluten_free', 'dairy_free'],
      macros: { protein: 50, carbs: 60, fat: 10, calories: 538 },
      ingredients: [
        { item: 'Pechuga de pollo', amount: 200, unit: 'g (por ración)' },
        { item: 'Quinoa', amount: 80, unit: 'g (seco, por ración)' },
        { item: 'Pimiento (rojo y verde)', amount: 100, unit: 'g (por ración)' },
        { item: 'Cebolla', amount: 50, unit: 'g (por ración)' },
        { item: 'Maíz dulce', amount: 60, unit: 'g (por ración)' },
        { item: 'AOVE + especias cajún', amount: 10, unit: 'g (por ración)' },
      ],
      steps: [
        'DÍA ANTERIOR: Marina 1 kg de pollo con especias cajún y AOVE durante la noche.',
        'Cuece 400 g de quinoa (seco) en 800 ml agua 15 min. Enfría.',
        'Cocina el pollo en batch: 220°C, 18-20 min en el horno.',
        'Saltea todos los pimientos y cebolla en batch.',
        'Divide en 5 tuppers: quinoa → pimiento → pollo → maíz.',
        'Refrigera. Se conserva 5 días. Los dos últimos días, congela.',
      ],
      nutritionist_note: 'El meal prep es la herramienta número 1 para la adherencia al plan nutricional. Estudios de compliance muestran que quien no prepara sus comidas con antelación tiene 3× más probabilidades de consumir opciones ultraprocesadas en comidas de trabajo o post-entreno tardío. La quinoa aguanta bien 5 días en frío sin perder textura. El pollo asado se mantiene jugoso mejor que el plancha al recalentar.',
    },
    {
      id: 26,
      name: 'Ensalada de garbanzos, pollo y feta (meal prep)',
      emoji: '🥗',
      scenario: ['meal_prep', 'cutting', 'lunch'],
      difficulty: 'low',
      prep_time: 15,
      servings: 1,
      budget_tier: 'low',
      dietary: ['gluten_free'],
      macros: { protein: 48, carbs: 38, fat: 14, calories: 474 },
      ingredients: [
        { item: 'Pechuga de pollo (asada)', amount: 150, unit: 'g' },
        { item: 'Garbanzos en conserva', amount: 120, unit: 'g' },
        { item: 'Queso feta', amount: 40, unit: 'g' },
        { item: 'Tomate cherry', amount: 80, unit: 'g' },
        { item: 'Pepino', amount: 80, unit: 'g' },
        { item: 'Aceitunas negras', amount: 20, unit: 'g' },
        { item: 'Limón + AOVE + orégano', amount: 15, unit: 'ml/g' },
      ],
      steps: [
        'Prepara el pollo asado en batch (ver receta Chicken Bowl).',
        'Lava y corta los vegetales.',
        'Monta la ensalada. Aliña con AOVE, limón y orégano.',
        'Guarda el aliño separado si se prepara para varios días.',
        'Se conserva 3 días en nevera sin aliñar.',
      ],
      nutritionist_note: 'Los garbanzos tienen un índice de saciedad de los más altos entre todos los alimentos, gracias a su combinación de proteína + fibra + almidón resistente. Esta ensalada no necesita calentarse, lo que la hace perfecta para oficina. El feta añade calcio y probióticos que mejoran la salud intestinal y la absorción de nutrientes.',
    },

    // ── CARGA DE CARBOHIDRATOS (competición) ─────────────────────────────────
    {
      id: 27,
      name: 'Plato de carga: pasta integral con pollo y brócoli',
      emoji: '🍝',
      scenario: ['carb_loading', 'pre_competition'],
      difficulty: 'low',
      prep_time: 20,
      servings: 1,
      budget_tier: 'low',
      dietary: ['dairy_free'],
      macros: { protein: 52, carbs: 95, fat: 8, calories: 664 },
      ingredients: [
        { item: 'Pasta integral (seco)', amount: 100, unit: 'g' },
        { item: 'Pechuga de pollo', amount: 180, unit: 'g' },
        { item: 'Brócoli', amount: 120, unit: 'g' },
        { item: 'Ajo (3 dientes)', amount: 9, unit: 'g' },
        { item: 'Aceite de oliva AOVE', amount: 10, unit: 'g' },
        { item: 'Sal, pimienta, orégano', amount: null, unit: null },
      ],
      steps: [
        'Cuece la pasta al dente (1 min menos de lo indicado).',
        'Cocina el pollo a la plancha. Corta en dados.',
        'Saltea el brócoli en ramilletes con ajo 4 min.',
        'Mezcla pasta, pollo y brócoli. Aliña con AOVE.',
        'Consume 3-4 h antes de la competición o sesión de alta intensidad.',
      ],
      nutritionist_note: 'La carga de carbohidratos es válida para eventos >90 min de alta intensidad. La pasta integral tiene un índice glucémico más bajo que la blanca, liberando glucosa gradualmente durante la competición. El brócoli aporta vitamina C que potencia la absorción del hierro del pollo. Evitar fibra extra (ensaladas, legumbres) en las últimas 24-48 h antes de la competición para minimizar el malestar gastrointestinal.',
    },
    {
      id: 28,
      name: 'Rice cakes con mantequilla de cacahuete (intra-entreno)',
      emoji: '🍡',
      scenario: ['intra_workout', 'carb_loading', 'snack'],
      difficulty: 'low',
      prep_time: 3,
      servings: 1,
      budget_tier: 'low',
      dietary: ['vegan', 'dairy_free'],
      macros: { protein: 10, carbs: 45, fat: 8, calories: 292 },
      ingredients: [
        { item: 'Tortas de arroz (sin sal)', amount: 60, unit: 'g (4-5 tortas)' },
        { item: 'Mantequilla de cacahuete 100%', amount: 20, unit: 'g' },
        { item: 'Miel', amount: 10, unit: 'g' },
        { item: 'Plátano (opcional)', amount: 60, unit: 'g' },
      ],
      steps: [
        'Extiende la mantequilla de cacahuete sobre las tortas de arroz.',
        'Añade un hilo de miel encima.',
        'Opcional: rodajas finas de plátano.',
        'Consumir en la pausa entre series o entre el calentamiento y la parte principal.',
      ],
      nutritionist_note: 'Las tortas de arroz tienen el índice glucémico más alto de los carbohidratos sólidos (IG 82), comparable al gel de glucosa. Esto las hace perfectas para recargar glucógeno durante sesiones de >90 min o entre entrenamientos dobles. La mantequilla de cacahuete añade grasas que ralentizan la absorción, convirtiendo el combo en de liberación escalonada: glucosa rápida + energía sostenida.',
    },

  ]; // fin ELITE_RECIPES

  // ── API de nutrición (info de macros FitSciPro) ────────────────────────────
  const MACRO_INFO = {
    protein: {
      icon: '🥩',
      title: 'PROTEÍNA',
      range: '2 – 2.4 g/kg · PESO CORPORAL',
      color: '#ff4757',
      description: 'El macronutriente más importante para la hipertrofia. Aporta los aminoácidos que construyen y reparan el tejido muscular. Fuentes de alta biodisponibilidad: pollo, pavo, ternera magra, huevos, pescado, lácteos, whey.',
      details: {
        volumen: '2 g/kg',
        definicion: '2.2–2.4 g/kg para preservar masa magra durante el déficit calórico.',
      },
    },
    carbs: {
      icon: '🌾',
      title: 'CARBOHIDRATOS',
      range: '3 – 6 g/kg · SEGÚN OBJETIVO',
      color: '#2196F3',
      description: 'El combustible principal para los entrenamientos de alta intensidad. El glucógeno muscular determina el rendimiento. No los elimines si quieres progresar en el gimnasio.',
      details: {
        volumen: '5–6 g/kg (superávit calórico)',
        definicion: '2–3 g/kg, priorizando el timing periéntreno.',
      },
    },
    fats: {
      icon: '🥑',
      title: 'GRASAS',
      range: '0.8 – 1.2 g/kg · PESO CORPORAL',
      color: '#f59e0b',
      description: 'Imprescindibles para la producción hormonal (testosterona, estrógenos), absorción de vitaminas liposolubles (A, D, E, K) y función cognitiva. Las grasas dietéticas NO se convierten directamente en grasa corporal — el exceso calórico total sí. Prioriza grasas insaturadas (omega-3, omega-9) y limita las saturadas y trans.',
      details: {
        volumen: '1.0–1.2 g/kg. No elimines las grasas para meter más hidratos; bajar de 0.7 g/kg reduce la testosterona y el rendimiento.',
        definicion: '0.8–1.0 g/kg. Recorta primero los hidratos, luego las grasas. Mantén omega-3 (salmón, sardinas, nueces) para preservar músculo.',
      },
    },
  };

  // ── Timing de nutrientes ───────────────────────────────────────────────────
  const TIMING_INFO = {
    pre: {
      title: 'VENTANA PRE-ENTRENO',
      slots: [
        {
          time: '2-3 h antes',
          label: 'COMIDA PRINCIPAL',
          color: '#ff4757',
          items: [
            'Comida completa: HC complejo + proteína moderada + poca grasa',
            'Objetivo: maximizar glucógeno y aminoácidos disponibles',
            'Ejemplos: pollo + arroz, pasta + atún',
          ],
        },
        {
          time: '30-45 min antes',
          label: 'SNACK',
          color: '#f59e0b',
          items: [
            'En ayunas no es necesario, pero en sesiones largas puede ayudar',
            '50-60 g de carbohidratos de rápida absorción + proteína opcional',
            'Ejemplos: plátano + scoop de whey, arroz inflado + batido',
          ],
        },
      ],
    },
    post: {
      title: 'POST-ENTRENO',
      slots: [
        {
          time: 'Dentro de 60 min',
          label: 'VENTANA ANABÓLICA',
          color: '#00d2ff',
          items: [
            'La síntesis proteica se eleva 24-48 h post-entreno; no solo la primera hora',
            'Proteína + CH en proporción 1:1 o 1:2 es óptimo',
            'Ejemplos: whey + plátano, arroz + pollo, batido de recuperación',
          ],
        },
      ],
    },
    principles: [
      'Proteína distribuida: Come 30-40 g de proteína cada 3-5 horas. Esto maximiza la síntesis proteica muscular durante todo el día.',
      'CH antes de entrenar: El superávit (volumen) > déficit (definición) es más importante que el timing aislado. Sin esto, nada funciona.',
      'CH al entrenar: Son tus aliados en volumen. Solo en pocas situaciones se recomienda limitar durante el entrenamiento.',
      'Hidratación: Mínimo 35 ml/kg. Por cada 1% de deshidratación el rendimiento baja un 2-5%.',
      'No temas los carbohidratos: La insulina no es el enemigo. Es un potente agente anabólico. Lo que importa es el balance calórico total.',
    ],
  };

  // ── Función pública: resolver placeholder de afiliado ─────────────────────
  function resolveAffiliateLink(placeholder) {
    if (!placeholder) return '#';
    const key = placeholder.replace(/[{}]/g, '');
    return AFFILIATE_LINKS[key] || '#';
  }

  // ── API pública ────────────────────────────────────────────────────────────
  return {
    AFFILIATE_LINKS,
    DONATION_LINKS,
    SPONSOR,
    SUPPLEMENTS,
    INGREDIENTS,
    ELITE_RECIPES,
    MACRO_INFO,
    TIMING_INFO,
    resolveAffiliateLink,
  };
})();
